# .github/workflows/deploy.yml
name: Deploy to S3 + CloudFront

on:
  workflow_dispatch: # 手動実行用のトリガーを追加
  push:
    branches: ["main"] # mainブランチにpushされた場合に実行

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Node.jsのバージョンに合わせる

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build # Reactのビルド

      - name: Configure AWS credentials
        # 公式のAWS Actions（OIDC連携 or シークレット）を設定
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1 # リージョンを合わせる

      - name: Sync build folder to S3
        run: aws s3 sync build/ s3://my-react-spa-bucket-example-2023 --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id EW3K1U49I9VB3 --paths "/*"
